### ISSUE TITLE
http to https redirect seems not working after configured socket activation

### ISSUE THREAD

**Issue by qupfer** [eriksjolund/podman-traefik-socket-activation#21]
Hi,

I used your example and works mostly fine. 

However, now every http request got me an 404. 

I tried router-based redirects

``` 
http:
  routers:
    router-aio:
      rule: "Host(`aio.mydomain.de`)"
      middlewares:
        - test-redirectscheme
      service: "aio"
      tls: {}
        #certresolver: "myresolver"

    router-nc-docker:
      rule: "Host(`nc.mydomain.de`)"
      service: "nc-docker"
      tls: {}

    router-kopia:
      rule: "Host(`kopia.mydomain.de`)"
      service: "kopia"
      tls:
        options: mtls@file

  middlewares:
    test-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

[...]
``` 

as a global one
```
Exec='--api.insecure=true' '--providers.docker=true' '--providers.file=true' '--providers.file.filename=/etc/traefik/file.yml' '--providers.file.watch=true' '--providers.docker.exposedbydefault=false' '--entryPoints.web=true'  '--entryPoints.web.forwardedHeaders.insecure=true'  '--entryPoints.websecure=true' '--entryPoints.websecure.forwardedHeaders.insecure=true' '--entryPoints.inform.address=:8080' '--entryPoints.traefik.address=:8082' 
'--entrypoints.web.http.redirections.entrypoint.to=websecure' '--entryPoints.web.http.redirections.entrypoint.scheme=https' 
``` 
Any ideas?

Thanks
